### ISSUE TITLE
image preview is stretched in 18:9 aspect ratio devices

### ISSUE THREAD

**Issue by returnZro** [xamarin/monodroid-samples#274]
On running the Camera2Basic in 18:9 screen aspect ratio devices, the image preview and captured image is getting stretched.

![screenshot_camera2basic](https://user-images.githubusercontent.com/38007133/41899321-cb5ab572-7949-11e8-8736-910522cf6dce.jpg)

**Comment by smvernon** [comment]
Hi, I was unable to replicate this issue on any of my devices. The issue seems like the preview size isn't getting set to optimal resolution. This won't fix the issue but might point you in the right direction, in SetUpCameraOutputs Try manually setting the 
Size largest = (Size)Collections.Max(Arrays.AsList(map.GetOutputSizes((int)ImageFormatType.Jpeg)),
                        new CompareSizesByArea());
To Size largest = new Size(1920, 1080);
If this fixes the preview then the issue might be with the default way of selecting the largest Image dimensions.

**Comment by alirong** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件。谢谢
