### ISSUE TITLE
BluetoothChat.BluetoothChatService.cs - clarify MY_UUID

### ISSUE THREAD

**Issue by majklf** [xamarin/monodroid-samples#90]
I tried this project and not worked. Then I discovered that the problem was in the wrong UUID. I entered 00001101-0000-1000-8000-00805F9B34FB and then worked. The value I got from bluetoothDevice.getUuids () [0] .getUuid () from the device to which i want to connect. So it seems that for CreateRfcommSocketToServiceRecord should use the UUID of the device and not from the application. If so, please modify the Commentary private static UUID MY_UUID

**Comment by Abhishekk360** [comment]
Thanks for reporting this issue. I have checked this issue with latest Updated sample. This issue is working fine. I have take another device and install bluetooth chat app and successfully able to communicate with the sample application. I am able to chat with the devices. Here is the screencast for the same: http://www.screencast.com/t/aSTtCFmH.

Hence closing this issue.

Thanks!
